### ISSUE TITLE
use --rx-flow when create port

### ISSUE THREAD

**Issue by YuanhWu** [usnistgov/ndn-dpdk#60] opened 2022-02-22 18:41 UTC
Hi,
I am using ndn-dpdk forwarder with commit #e9ed89 to do a test. I have two servers now, one is acting as a consumer node and one is acting as a producer node. I run ndn-dpdk forwarder on both two servers and enable "`--rx-flow 1`" **only on server1**(consumer node). The problem is, if I do not use "--rx-flow”, I can successfully send Interest packets from server1 to server2 and get data back. If I use "--rx-flow", the data packets are sent back by server2 but server1 cannot receive data packets successfully(rxData counter at server1 is 0). 

- This is the NIC I use: `MT27800 Family [ConnectX-5]`

- Configure file at server1: 

```bash
jq -n '{
  eal: {
    coresPerNuma: { "0": 10, "1": 0 },
    memPerNuma: { "0": 51200, "1": 4096 }
  },
  lcoreAlloc: {
    RX: { "0": 3, "1": 0 },
    TX: { "0": 3, "1": 0 },
    #CRYPTO: { "0": 1, "1": 0 },
    FWD: { "0": 3, "1": 0 }
  },
  ndt:{prefixLen: 4},
  mempool: {
    DIRECT: { capacity: 3145727, dataroom: 9146 },
    INDIRECT: { capacity: 1048575 }
  },
  pcct: {
    pcctCapacity: 65535,
    csMemoryCapacity: 1,
    csIndirectCapacity: 1
  }
}' | sudo docker run -i --rm ndndpdkimg:e9ed8 ndndpdk-ctrl --gqlserver $GQLFW activate-forwarder

#port
sudo docker run -i --rm ndndpdkimg:e9ed8 ndndpdk-ctrl --gqlserver $GQLFW create-eth-port --pci 3b:00.0 --mtu 9000 --rx-flow 1

#face
FACEID=$(jq -n '{
  scheme: "ether",
  #portConfig: {mtu: 9000},
  local: "24:8a:07:b5:95:da",
  remote: "24:8a:07:b4:32:fa",
  mtu: 9000,
  vlan: 1627,
}' | sudo docker run -i --rm ndndpdkimg:e9ed8 ndndpdk-ctrl --gqlserver $GQLFW create-face | tee /dev/stderr | jq -r .id)

#fib
sudo docker run -i --rm ndndpdkimg:e9ed8 ndndpdk-ctrl --gqlserver $GQLFW insert-fib --name /ndnc/ft --nexthop $FACEID
```

- Logs at server1:

```
neu@dtn103:~$ sudo docker logs -f fw2
{"level":"info","ts":1645554333.6659207,"logger":"ethport","msg":"destroy RxFlow success","port":0,"face":44633}
{"level":"info","ts":1645554333.666222,"logger":"ethport","msg":"face stopped","port":0,"id":44633}
{"level":"info","ts":1645554333.7268565,"logger":"ethdev","msg":"ethdev stopped and closed","id":0,"name":"0000:3b:00.0"}
{"level":"info","ts":1645554333.726895,"logger":"ethport","msg":"port closed","port":0}
{"level":"info","ts":1645554334.9039006,"logger":"main","msg":"NDN-DPDK service starting","version":"v0.0.0-20220218161704-e9ed8955a5df","uid":0,"linux":"5.4.0-89-generic","dpdk":"22.03.0-rc1","spdk":"22.01"}
{"level":"info","ts":1645554334.9044626,"logger":"main","msg":"GraphQL HTTP server starting","listen":":3030"}
{"level":"info","ts":1645554338.2673528,"logger":"main","msg":"activate start","role":"forwarder"}
{"level":"warn","ts":1645554338.3179905,"logger":"DPDK","msg":"EAL: No free 2048 kB hugepages reported on node 0"}
{"level":"warn","ts":1645554338.318047,"logger":"DPDK","msg":"EAL: No free 2048 kB hugepages reported on node 1"}
{"level":"error","ts":1645554338.3182583,"logger":"DPDK","msg":"EAL: Cannot open VFIO container /dev/vfio/vfio, error 2 (No such file or directory)"}
{"level":"info","ts":1645554338.318277,"logger":"DPDK","msg":"EAL: VFIO support could not be initialized"}
{"level":"warn","ts":1645554338.6272235,"logger":"DPDK.0","msg":"TELEMETRY: No legacy callbacks, legacy socket not created"}
{"level":"info","ts":1645554338.6272519,"logger":"ealinit","msg":"EAL ready","args":"-l 0,2,4,6,8,10,12,14,16,18 --socket-limit 51200,4096 --in-memory --single-file-segments -d /usr/local/lib/dpdk/pmds-22.1 -a 00:00.0","main":0,"workers":[2,4,6,8,10,12,14,16,18],"sockets":[0]}
{"level":"info","ts":1645554338.6378443,"logger":"SPDK.0","msg":"SPDK logger ready"}
{"level":"info","ts":1645554338.654408,"logger":"spdkenv","msg":"SPDK thread created","name":"K0000000000000001","th":6388879872,"spdk-thread":140035398014576}
{"level":"info","ts":1645554338.6558483,"logger":"ealthread","msg":"lcores configured","role":"FWD","lc":[2,4,6]}
{"level":"info","ts":1645554338.6558607,"logger":"ealthread","msg":"lcores configured","role":"RX","lc":[8,10,14]}
{"level":"info","ts":1645554338.655863,"logger":"ealthread","msg":"lcores configured","role":"TX","lc":[12,16,18]}
{"level":"info","ts":1645554338.6666598,"logger":"pcct","msg":"init","pcct":6384877376,"mp":6384877184,"token-ht":6287310208}
{"level":"info","ts":1645554338.6666703,"logger":"pit","msg":"init","pcct":6384877376,"pit":6384877408}
{"level":"info","ts":1645554338.6666958,"logger":"cs","msg":"init","pcct":6384877376,"cs":6384877504,"cap-memory":64,"cap-disk":0,"cap-indirect":64}
{"level":"info","ts":1645554338.6667044,"logger":"MinTmr","msg":"New","sched":"0x1768fbb00","slots":"4096","interval":"99666666","cb":"0x98a110"}
{"level":"info","ts":1645554345.6327033,"logger":"pcct","msg":"init","pcct":7109478464,"mp":7109478272,"token-ht":7011911296}
{"level":"info","ts":1645554345.6327646,"logger":"pit","msg":"init","pcct":7109478464,"pit":7109478496}
{"level":"info","ts":1645554345.6328337,"logger":"cs","msg":"init","pcct":7109478464,"cs":7109478592,"cap-memory":64,"cap-disk":0,"cap-indirect":64}
{"level":"info","ts":1645554345.6330204,"logger":"MinTmr","msg":"New","sched":"0x1a1c04400","slots":"4096","interval":"99666666","cb":"0x98a110"}
{"level":"info","ts":1645554345.635663,"logger":"pcct","msg":"init","pcct":7005550208,"mp":7005550016,"token-ht":6907983040}
{"level":"info","ts":1645554345.6356704,"logger":"pit","msg":"init","pcct":7005550208,"pit":7005550240}
{"level":"info","ts":1645554345.635701,"logger":"cs","msg":"init","pcct":7005550208,"cs":7005550336,"cap-memory":64,"cap-disk":0,"cap-indirect":64}
{"level":"info","ts":1645554345.635808,"logger":"MinTmr","msg":"New","sched":"0x19b8e7240","slots":"4096","interval":"99666666","cb":"0x98a110"}
{"level":"info","ts":1645554345.6388514,"logger":"FwFwd.2","msg":"Run","fwd-id":"0","fwd":"0x17cc18a40","fib":"0x19b8e70c0","pit":"0x17c917f60","cs":"0x17c917fc0","crypto":"(nil)"}
{"level":"info","ts":1645554345.6388986,"logger":"FwFwd.4","msg":"Run","fwd-id":"1","fwd":"0x1a7f21340","fib":"0x19b8e70c0","pit":"0x1a7c20860","cs":"0x1a7c208c0","crypto":"(nil)"}
{"level":"info","ts":1645554345.6390262,"logger":"FwFwd.6","msg":"Run","fwd-id":"2","fwd":"0x1a1c04180","fib":"0x19b8e70c0","pit":"0x1a19036a0","cs":"0x1a1903700","crypto":"(nil)"}
{"level":"info","ts":1645554345.6392376,"logger":"main","msg":"activate success","role":"forwarder"}
{"level":"info","ts":1645554346.3656387,"logger":"eal","msg":"PCI device probed","addr":"0000:3b:00.0","args":""}
{"level":"info","ts":1645554346.6072228,"logger":"ethdev","msg":"ethdev started","id":0,"name":"0000:3b:00.0","driver":"mlx5_pci","mtu":9000,"rxq":1,"txq":1,"promisc":false}
{"level":"info","ts":1645554346.6072962,"logger":"ethport","msg":"port opened","port":0,"rxImpl":"RxFlow"}
{"level":"info","ts":1645554347.1694493,"logger":"ethport","msg":"create RxFlow success","port":0,"queues":[0],"face":7123}
{"level":"info","ts":1645554347.1694825,"logger":"ethport","msg":"face started","port":0,"id":7123}
{"level":"info","ts":1645554347.1694973,"logger":"iface","msg":"face created","id":7123,"socket":0,"mtu":9000,"locator":{"local":"24:8a:07:b5:95:da","remote":"24:8a:07:b4:32:fa","scheme":"ether","vlan":1627}}
{"level":"warn","ts":1645554372.1564474,"logger":"DPDK","msg":"rte_pmd_memif_probe(): Failed to register mp action callback: Operation not supported"}
{"level":"info","ts":1645554372.156469,"logger":"eal","msg":"vdev initialized","name":"net_memifK000000000000001e","args":"id=0,role=server,bsize=9000,rsize=12,socket=/run/ndn/ndnc-memif-140-1645554372154166594.sock,socket-abstract=no,mac=F2:6D:65:6D:69:66","socket":"any"}
{"level":"info","ts":1645554372.1565197,"logger":"ethport","msg":"port opened","port":1,"rxImpl":"RxMemif"}
{"level":"info","ts":1645554372.1568003,"logger":"ethdev","msg":"ethdev started","id":1,"name":"net_memifK000000000000001e","driver":"net_memif","mtu":9000,"rxq":1,"txq":1,"promisc":false}
{"level":"info","ts":1645554372.156818,"logger":"ethport","msg":"face started","port":1,"id":40821}
{"level":"info","ts":1645554372.1568255,"logger":"iface","msg":"face created","id":40821,"socket":0,"mtu":9000,"locator":{"dataroom":9000,"id":0,"ringCapacity":4096,"role":"server","rxQueueSize":64,"scheme":"memif","socketName":"/run/ndn/ndnc-memif-140-1645554372154166594.sock","txQueueSize":64}}
{"level":"info","ts":1645554373.555973,"logger":"ethport","msg":"face stopped","port":1,"id":40821}
{"level":"info","ts":1645554373.5562184,"logger":"eal","msg":"vdev uninitialized","name":"net_memifK000000000000001e"}
{"level":"info","ts":1645554373.556229,"logger":"ethdev","msg":"ethdev stopped and closed","id":1,"name":"net_memifK000000000000001e"}
{"level":"info","ts":1645554373.5562334,"logger":"ethport","msg":"port closed","port":1}
```

**Comment by yoursunny** [comment] 2022-02-22 19:30
As explained in `docs/face.md`:

> Enabling RxFlow on a NIC that does not support it causes either port creation failure or face creation failure.

In your logs, both port creation and face creation succeeded, which means the device supports rte\_flow API.
Occasionally, DPDK drivers may successfully activate rte\_flow even if certain features or combinations are not supported.
I've seen such situation several times, and this might be what's happening.

Has the same NIC worked with RxFlow mode in the past?
If so, this might be a regression in DPDK v22.03-rc1.

There's also a possibility that the remote node did not encode the packet correctly, or there's some intermediate network equipment mangling the packets.
The packets got accepted in RxTable mode because its checking logic is less strict than the hardware rte\_flow rules.
To see the incoming packets, you can create the port with AF\_PACKET driver, and then run `tcpdump` to collect traffic traces.

**Comment by Pesa** [comment] 2022-02-22 19:36
> Has the same NIC worked with RxFlow mode in the past? If so, this might be a regression in DPDK v22.03-rc1.

It was similarly broken with a ndn-dpdk commit from Dec 28.

**Comment by YuanhWu** [comment] 2022-02-22 20:03
1. Server 1 is not used for test before, but server2 was used successfully during SC21. At that time, we still used an old version of ndn-dpdk (an October or November commit). In that commit, we did not create a port like this. Is "--rx-flow" enabled as default in the old version?
2. If I enable "--rx-flow" on server2, it also has a similar problem now.
3. The firmware version at Server1: `fw_ver: 16.32.1010`, which is already the latest one I can find on the Mellanox website.

**Comment by yoursunny** [comment] 2022-02-22 20:15
> At that time, we still used an old version of ndn-dpdk (an October or November commit). In that commit, we did not create a port like this. Is "--rx-flow" enabled as default in the old version?

In the past, NDN-DPDK will attempt to create a port with RxFlow mode.
If that fails, it changes to RxTable mode.
The only way to make sure is by reading the logs.

My guess is that in the older version you are using RxFlow, because the fallback logic I had in the past would have concluded that the NIC supports RxFlow when face creation succeeds, which is the case you are seeing today.

**Comment by Pesa** [comment] 2022-02-22 20:21
@yoursunny I assume you cannot reproduce the problem on NIST machines with ConnectX-5? Note the mtu=9000 and vlan usage.

> My guess is that in the older version you are using RxFlow, because the fallback logic I had in the past would have concluded that the NIC supports RxFlow when face creation succeeds, which is the case you are seeing today.

I think so too. Also, I don't remember seeing errors related to RxFlow when I was helping in the days before the SC21 demo (although maybe I never saw the logs from this particular machine).

**Comment by YuanhWu** [comment] 2022-02-22 20:30
Thanks for the answer! Also, these are the data packets I catch:
```
root@ea8efc83b8c1:/# tcpdump -XX -vv -i p1p1
tcpdump: listening on p1p1, link-type EN10MB (Ethernet), snapshot length 262144 bytes
20:25:47.593227 24:8a:07:b4:32:fa (oui Unknown) > 24:8a:07:b5:95:da (oui Unknown), ethertype Unknown (0x8624), length 211:
        0x0000:  248a 07b5 95da 248a 07b4 32fa 8100 265b  $.....$...2...&[
        0x0010:  8624 64bf 6207 f4ff ffff ffff 0050 b406  .$d.b........P..
        0x0020:  b207 2c08 046e 646e 6308 0266 7408 0974  ..,..ndnc..ft..t
        0x0030:  6573 7433 2e74 7874 2008 6d65 7461 6461  est3.txt..metada
        0x0040:  7461 3608 16d6 3582 4b88 99ad 3201 0014  ta6...5.K...2...
        0x0050:  0b19 0400 0000 011a 0332 0100 156e 071f  .........2...n..
        0x0060:  0804 6e64 6e63 0802 6674 0809 7465 7374  ..ndnc..ft..test
        0x0070:  332e 7478 7436 0816 d635 77b9 f4f3 531a  3.txt6...5w...S.
        0x0080:  0332 0101 fdf5 0002 03e8 fdf5 0208 0000  .2..............
        0x0090:  0000 0000 0400 fdf5 0402 81a4 fdf5 0608  ................
        0x00a0:  16d6 3577 b9f4 f353 fdf5 0808 16d6 3577  ..5w...S......5w
        0x00b0:  b9f4 f353 fdf5 0a08 16d6 3577 b9f4 f353  ...S......5w...S
        0x00c0:  fdf5 0c08 16d6 3577 b9f4 f353 1603 1b01  ......5w...S....
        0x00d0:  c817 00                                  ...
20:25:47.624793 24:8a:07:b4:32:fa (oui Unknown) > 24:8a:07:b5:95:da (oui Unknown), ethertype Unknown (0x8624), length 1093:
        0x0000:  248a 07b5 95da 248a 07b4 32fa 8100 265b  $.....$...2...&[
        0x0010:  8624 64fd 042f 6207 f5ff ffff ffff 0050  .$d../b........P
        0x0020:  fd04 2206 fd04 1e07 2208 046e 646e 6308  .."....."..ndnc.
        0x0030:  0266 7408 0974 6573 7433 2e74 7874 3608  .ft..test3.txt6.
        0x0040:  16d6 3577 b9f4 f353 3201 0014 051a 0332  ..5w...S2......2
        0x0050:  0101 15fd 03e8 0000 0000 0000 0000 0000  ................
        0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0070:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0080:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0090:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0100:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0110:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0120:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0130:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0140:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0150:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0160:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0170:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0180:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0190:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0200:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0210:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0220:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0230:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0240:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0250:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0260:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0270:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0280:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0290:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0300:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0310:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0320:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0330:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0340:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0350:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0360:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0370:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0380:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0390:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0400:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0410:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0420:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0430:  0000 0000 0000 0000 0000 0000 0000 1603  ................
        0x0440:  1b01 c817 00                             .....
20:25:47.624796 24:8a:07:b4:32:fa (oui Unknown) > 24:8a:07:b5:95:da (oui Unknown), ethertype Unknown (0x8624), length 109:
        0x0000:  248a 07b5 95da 248a 07b4 32fa 8100 265b  $.....$...2...&[
        0x0010:  8624 6459 6207 f6ff ffff ffff 0050 4e06  .$dYb........PN.
        0x0020:  4c07 2208 046e 646e 6308 0266 7408 0974  L."..ndnc..ft..t
        0x0030:  6573 7433 2e74 7874 3608 16d6 3577 b9f4  est3.txt6...5w..
        0x0040:  f353 3201 0114 051a 0332 0101 1518 0000  .S2......2......
        0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0060:  0000 0000 0000 1603 1b01 c817 00         .............
```

**Comment by Pesa** [comment] 2022-02-22 20:37
Thanks @YuanhWu.
Looks like the PCP of the 802.1Q tag is set to 2. We saw the same (or a similar) problem during the SC21 demo where ndn-dpdk was dropping incoming frames with PCP != 0. @yoursunny could this be the cause?

**Comment by yoursunny** [comment] 2022-02-22 20:45
>         0x0000:  248a 07b5 95da 248a 07b4 32fa 8100 265b  $.....$...2...&[
>         0x0010:  8624 64bf 6207 f4ff ffff ffff 0050 b406  .$d.b........P..

The VLAN header is a little concerning: it has a non-zero value in the *Priority* field.
This had caused problems in the past.

https://github.com/usnistgov/ndn-dpdk/blob/e9ed8955a5df26c978066e4cfe7bf87e7b2b44d0/csrc/ethface/locator.c#L293
While I've been telling rte\_flow not to care about this field, it's possible that the driver cannot process it properly.

I'll double check this with a simplified program, and then report to DPDK bug tracker.

**Comment by yoursunny** [comment] 2022-02-23 00:01
I made a small C program to verify rte\_flow behavior.

```c
/*
gcc -m64 -pthread -O3 -g -march=native -o x x.c $(pkg-config --cflags --libs libdpdk)

MODE=10 # RX without flow
MODE=11 # RX with flow
MODE=20 # TX with vlan.Priority=0
MODE=21 # TX with vlan.Priority=1
MTU=9000
sudo ./x -d /usr/local/lib/librte_mempool_ring.so -d /usr/local/lib/librte_net_mlx5.so \
  -l 1 -n 2 --huge-unlink -a 5e:00.0 -- $MODE $MTU
*/

#include <inttypes.h>
#include <stdbool.h>
#include <time.h>

#include <rte_config.h>

#include <rte_eal.h>
#include <rte_ethdev.h>
#include <rte_ether.h>
#include <rte_flow.h>
#include <rte_lcore.h>
#include <rte_malloc.h>
#include <rte_mbuf.h>
#include <rte_memcpy.h>

static int mode = 0;
static int mtu = 0;

static uint8_t* payload = NULL;

static struct rte_mempool* mp = NULL;

static uint16_t port = RTE_MBUF_PORT_INVALID;

static const uint16_t vlanID = 1627;

static void
rxMakeFlow()
{
  struct rte_flow_attr attr = { .ingress = true };

  struct rte_flow_item_eth ethSpec = { 0 };
  rte_memcpy(&ethSpec.hdr.dst_addr, "\x02\x00\x00\x00\x00\x01", RTE_ETHER_ADDR_LEN);
  rte_memcpy(&ethSpec.hdr.src_addr, "\x02\x00\x00\x00\x00\x00", RTE_ETHER_ADDR_LEN);
  ethSpec.hdr.ether_type = rte_cpu_to_be_16(RTE_ETHER_TYPE_VLAN);
  struct rte_flow_item_eth ethMask = { 0 };
  memset(&ethMask.hdr, 0xFF, RTE_ETHER_HDR_LEN);
  struct rte_flow_item_vlan vlanSpec = { 0 };
  vlanSpec.hdr.vlan_tci = rte_cpu_to_be_16(vlanID);
  vlanSpec.hdr.eth_proto = rte_cpu_to_be_16(0x7000);
  struct rte_flow_item_vlan vlanMask = { 0 };
  vlanMask.hdr.vlan_tci = rte_cpu_to_be_16(0x0FFF);
  vlanMask.hdr.eth_proto = rte_cpu_to_be_16(0xFFFF);

  struct rte_flow_item pattern[] = {
    {
      .type = RTE_FLOW_ITEM_TYPE_ETH,
      .spec = &ethSpec,
      .mask = &ethMask,
    },
    {
      .type = RTE_FLOW_ITEM_TYPE_VLAN,
      .spec = &vlanSpec,
      .mask = &vlanMask,
    },
    {
      .type = RTE_FLOW_ITEM_TYPE_END,
    },
  };

  struct rte_flow_action_queue queue = { .index = 0 };
  struct rte_flow_action actions[] = {
    {
      .type = RTE_FLOW_ACTION_TYPE_QUEUE,
      .conf = &queue,
    },
    { .type = RTE_FLOW_ACTION_TYPE_END },
  };

  struct rte_flow* flow = rte_flow_create(port, &attr, pattern, actions, NULL);
  RTE_VERIFY(flow != NULL);
}

static void
rxLoop()
{
  while (true) {
    struct rte_mbuf* burst[64];
    uint16_t received = rte_eth_rx_burst(port, 0, burst, RTE_DIM(burst));
    if (received > 0) {
      struct rte_mbuf* m = burst[0];
      printf("RX %" PRIu16 " %" PRIu32 " %" PRIu16 " ", received, m->pkt_len, m->data_len);

      uint8_t* buf = rte_pktmbuf_mtod(m, uint8_t*);
      for (uint16_t i = 0;
           i < RTE_MIN(m->data_len, RTE_ETHER_HDR_LEN + sizeof(struct rte_vlan_hdr)); ++i) {
        printf("%02x", buf[i]);
      }
      printf("\n");
      rte_pktmbuf_free_bulk(burst, received);
    }
  }
}

static void
txLoop(uint8_t vlanPriority)
{
  struct rte_ether_hdr eth = { 0 };
  rte_memcpy(&eth.dst_addr, "\x02\x00\x00\x00\x00\x01", RTE_ETHER_ADDR_LEN);
  rte_memcpy(&eth.src_addr, "\x02\x00\x00\x00\x00\x00", RTE_ETHER_ADDR_LEN);
  eth.ether_type = rte_cpu_to_be_16(RTE_ETHER_TYPE_VLAN);
  struct rte_vlan_hdr vlan = { 0 };
  vlan.vlan_tci = rte_cpu_to_be_16((vlanPriority << 13) | vlanID);
  vlan.eth_proto = rte_cpu_to_be_16(0x7000);

  while (true) {
    struct rte_mbuf* m = rte_pktmbuf_alloc(mp);
    RTE_VERIFY(m != NULL);

    char* room = rte_pktmbuf_append(m, mtu);
    RTE_VERIFY(room != NULL);
    rte_memcpy(room, payload, mtu);
    room = rte_pktmbuf_prepend(m, RTE_ETHER_HDR_LEN + sizeof(struct rte_vlan_hdr));
    RTE_VERIFY(room != NULL);
    rte_memcpy(room, &eth, RTE_ETHER_HDR_LEN);
    rte_memcpy(RTE_PTR_ADD(room, RTE_ETHER_HDR_LEN), &vlan, sizeof(vlan));

    uint16_t sent = rte_eth_tx_burst(port, 0, &m, 1);
    if (sent == 0) {
      rte_pktmbuf_free(m);
    }
  }
}

int
main(int argc, char** argv)
{
  int res = rte_eal_init(argc, argv);
  RTE_VERIFY(res >= 0);

  mode = atoi(argv[res + 1]);
  mtu = atoi(argv[res + 2]);

  payload = rte_zmalloc("", mtu, 0);
  for (int i = 0; i < mtu; ++i) {
    payload[i] = (uint8_t)i;
  }

  mp = rte_pktmbuf_pool_create(
    "MP", 65535, 0, 0, RTE_PKTMBUF_HEADROOM + RTE_ETHER_HDR_LEN + sizeof(struct rte_vlan_hdr) + mtu,
    rte_socket_id());
  RTE_VERIFY(mp != NULL);

  port = rte_eth_find_next(0);
  RTE_VERIFY(rte_eth_dev_is_valid_port(port));

  struct rte_eth_conf ethconf = { 0 };
  ethconf.rxmode.mtu = mtu;
  res = rte_eth_dev_configure(port, 1, 1, &ethconf);
  RTE_VERIFY(res == 0);

  res = rte_eth_dev_set_mtu(port, mtu);
  RTE_VERIFY(res == 0);

  res = rte_eth_rx_queue_setup(port, 0, 1024, rte_eth_dev_socket_id(port), NULL, mp);
  RTE_VERIFY(res == 0);
  res = rte_eth_tx_queue_setup(port, 0, 1024, rte_eth_dev_socket_id(port), NULL);
  RTE_VERIFY(res == 0);

  if (mode == 11) {
    res = rte_flow_isolate(port, 1, NULL);
    RTE_VERIFY(res == 0);
  }

  res = rte_eth_dev_start(port);
  RTE_VERIFY(res == 0);

  res = rte_eth_promiscuous_enable(port);
  RTE_VERIFY(res == 0);

  switch (mode) {
    case 11:
      rxMakeFlow();
      // fallthrough
    case 10:
      rxLoop();
      break;
    case 20:
      txLoop(0);
      break;
    case 21:
      txLoop(1);
      break;
  }

  return 0;
}
```

To use this program:

* Specify the PCI address of the NIC in `-a` flag.
* If your switch has MAC address filtering or needs specific VLAN numbers, modify these in the code.
* Transmit with `MODE=20` or `MODE=21`.
* Receive with `MODE=10` or `MODE=11`.
* Upon receiving a non-empty burst, you'll see a line: number of packets in the burst, size of the first packet, Ethernet+VLAN header of the first packet.
* You can also receive with `tcpdump` when the program is not running.

If you can receive with `MODE=10` but cannot receive with `MODE=11`, it means the NIC driver may not support rte\_flow properly; in that case, there's nothing I can do in NDN-DPDK, and we have to report to DPDK project.
If this test program shows no problem, it's more likely that I broke something in NDN-DPDK.

**Comment by YuanhWu** [comment] 2022-02-23 01:13
Hi @yoursunny  I use `MODE=21` at server1 and `MODE=11` at server2. It looks fine and I can see the output like this: 
```
RX 63 9018 9018 0200000000010200000000008100265a7000
RX 11 9018 9018 0200000000010200000000008100265a7000
```

**Comment by yoursunny** [comment] 2022-02-23 01:14
> I use `MODE=21` at server1 and `MODE=11` at server2. It looks fine and I can see the output like this:

This means there's no problem with DPDK drivers.

**Comment by yoursunny** [comment] 2022-02-23 01:18
I did some tests and found two potential mistakes in NDN-DPDK's rte\_flow pattern construction:

* For VLAN, the pattern asks the driver to match VLAN ID only without matching EtherType, while the intention is to match both.
* For UDP, the pattern asks the driver to match destination port only, while the intention is to match both source and destination ports.

It seems to cause matching errors when VLAN headers are used, regardless of MTU or Docker containers.

---

I am currently fixing both issues.
However, there are other things broken due to the TxLoop refactoring from last week.
So far I noticed that I can't create more than one port and NDT updates may crash.
I'll get them resolved within next few days.

If you want to try out the rte\_flow pattern fix, cherry-pick https://github.com/yoursunny/ndn-dpdk/commit/33208790fb24be881c03ef6ec60bce926546b6f8 without pulling other commits.

**Comment by YuanhWu** [comment] 2022-02-23 01:23
OK, thanks!

**Comment by yoursunny** [comment] 2022-02-23 19:06
> So far I noticed that I can't create more than one port and NDT updates may crash.

Other bugs are fixed and the the rte\_flow pattern fix is pushed.

**Closed by yoursunny** 2022-02-23 19:06 UTC

**Comment by Pesa** [comment] 2022-02-23 19:43
@YuanhWu can you confirm the latest commit fixes the issue?

**Comment by YuanhWu** [comment] 2022-02-23 20:59
> @YuanhWu can you confirm the latest commit fixes the issue?

Thank @yoursunny , @Pesa . It's fixed.
