### ISSUE TITLE
Connection: NDN-DPDK to NFD (how to restart 'ndndpdk-svc service' process)

### ISSUE THREAD

**Issue by Code-shaker** [usnistgov/ndn-dpdk#16] opened 2021-07-14 15:24 UTC
Local Communication over Unix Socket (second part)

Consumer for prefix `/app/B` connects to NDN-DPDK

after I create a face I've got this:

```text
Executing query... error
Error:  {
  data: null,
  errors: [
    {
      message: 'dial unix /run/ndn/nfd.sock: connect: no such file or directory',
      locations: [Array],
      path: [Array]
    }
  ]
}
```

I am new on NDN enviroment, need some help.
I think to activate NDN-DPDK forwarder again, to run the scenario of NDN-DPDK forwarder and NFD correctly.

**Comment by yoursunny** [comment] 2021-07-14 17:37
> dial unix /run/ndn/nfd.sock: connect: no such file or directory

This means either NFD is not running, or its Unix socket is not mounted into the NDN-DPDK container at `/run/ndn/nfd.sock`.

Note that the NFD container given in the example has changed NFD's Unix socket path from the default `/run/nfd.sock` to `/run/ndn/nfd.sock`:
https://github.com/usnistgov/ndn-dpdk/blob/1c9ce3a328284312d3fe128eae872d43bb7595f5/docs/interop/nfd/start.sh#L23
This change is made to prevent NFD and related applications from having access to other sockets under `/run` (such as the Docker socket).

**Comment by Code-shaker** [comment] 2021-07-14 19:16
> Unix socket is not mounted into the NDN-DPDK container
yes, the reason therefore is that I am not prepared the `NDN-DPDK Docker Container`

**Comment by yoursunny** [comment] 2021-07-15 21:49
According to the last comment, this is user error and not a bug, so I'm closing this issue.
If you still think there's a bug, please comment and I'll reopen.

**Closed by yoursunny** 2021-07-15 21:49 UTC
